### ISSUE TITLE
Support query explanations

### ISSUE THREAD

**Issue by jasona** [atheken/NoRM#1]
See http://www.mongodb.org/display/DOCS/Optimization#Optimization-Explain

(putting this in so we don't forget later; doesn't seem like a v1 thing to me)

**Comment by TylerBrinks** [comment]
Pushed - needs to be merged to Andrew's unstable branch.  May be more to do yet, but it's a great start (specifically adding indexes).

**Comment by atheken** [comment]
sweet!
