### ISSUE TITLE
Cannot ignore properties when serializing

### ISSUE THREAD

**Issue by JornWildt** [atheken/NoRM#10]
There seems to be no way to tell the BSON serializer that it should ignore certain properties.

**Comment by atheken** [comment]
The MongoIgnore attribute serves this purpose.

**Comment by JornWildt** [comment]
I haven't tried this, but I assume you add this as an attribute on your domain objects? In that case I would rather not use it, since it leaks the persistence layer into the domain objects.

You already have MongoConfiguration.Initialize with config.For<T> where you can configure some persistence properties outside of the domain objects. Why not add it here. For instance like:

```
    MongoConfiguration.Initialize(config =>
    {
      config.For<MyDomainObject>(c =>
      {
        c.ForProperty(b => b.ExtraProperty).Ignore();
      });
    });
```

**Comment by atheken** [comment]
That looks like a useful addition to the configuration component. Feel free to fork it and implement it, or post a request to the Google Group.
