### ISSUE TITLE
Cannot serialize Expando objects as properties of Expando objects

### ISSUE THREAD

**Issue by JornWildt** [atheken/NoRM#13]
All properties of an Expando is serialized using SerializeMember. This in turn does not call WriteDocument, but only WriteObject, which means any inner Expando objects are serialized as "real" objects. This again means deserialization fails.

This is not an issue for me, and apparently not any one else, so maybe it's not that important?

**Comment by atheken** [comment]
I think that when the type is unknown, it needs to be deserialized as an expando.

**Comment by atheken** [comment]
I think this is now resolved.
