### ISSUE TITLE
Getting "Connection timeout"

### ISSUE THREAD

**Issue by ArnisL** [atheken/NoRM#14]
Any ideas why this exception is thrown every ~5 minutes?

[MongoException: Connection timeout trying to get connection from connection pool]
   Norm.PooledConnectionProvider.Open(String options) in D:\Coding\DotNet\OS\NoRM\NoRM\Connections\PooledConnectionProvider.cs:62
   Norm.Mongo.ServerConnection() in D:\Coding\DotNet\OS\NoRM\NoRM\Mongo.cs:189
   Norm.Mongo..ctor(String db, String server, String port, String options) in D:\Coding\DotNet\OS\NoRM\NoRM\Mongo.cs:90
   Norm.Mongo..ctor(String db) in D:\Coding\DotNet\OS\NoRM\NoRM\Mongo.cs:44

**Comment by atheken** [comment]
Without seeing some code it's hard to tell, two things:

1) Please post this to the google group: http://groups.google.com/group/norm-mongodb?lnk=srg

2) Are you disposing "Mongo" after you're done with it? Each instance of this class has connection affinity, and will not release its pooled connection until it is disposed. It would be useful to see how you're using this class in your code.

**Comment by ArnisL** [comment]
Sorry for my ignorance. Will use google group in advance.

It looks like life cycle management is wrong and Disposed isn't called.

Thanks.

**Comment by atheken** [comment]
Sorry, does that mean you're not disposing Mongo? or that you think there's a bug in norm? can you post some of the code you're using to access Mongo via NoRM?

http://gist.github.com

**Comment by ArnisL** [comment]
Yeah, my code was wrong. NoRM looks good.

**Comment by vgirard** [comment]
How did you resolve this, I have the same issue, I'm using Ninject so the connection should be close by ninject? Any help please!

**Comment by atheken** [comment]
@vgirard you should post your Ninject code to the Google Group and I am sure someone can help you out.

**Comment by ArnisL** [comment]
@vgirard I just ensured correct life cycle. MongoSession has to be released at the end of http request or something. Played around structuremap a bit and it worked.
