### ISSUE TITLE
Count() method coming from IQueryable interface throws assertions on server

### ISSUE THREAD

**Issue by ti24horas** [atheken/NoRM#15]
When i call Count() method from IQueryable interface without query parameters, the server throws the following assertion:
server log with(-vvvv specified):
Thu Jul 01 20:46:04 run command databasetest.$cmd { query: { count: "Product", query: {} } }
Thu Jul 01 20:46:04 query galeriadoamor.com.$cmd ntoreturn:1 0ms
Thu Jul 01 20:46:04   Assertion failure toSend.data util\message.cpp 380
Thu Jul 01 20:46:04   AssertionException in connThread, closing client connection

The code i tested is:

long count = db.GetCollection<Product>().FindAll().Count();
The class description is pasted below:

public class Product
    {
        [MongoIdentifier]
        public int? ID { get; set; }
        public List<ProductDescription> AvailableDescriptions { get; set; }

```
    public double Weight { get; set; }

    public string InternalName { get; set; }
}
public class ProductDescription
{
    public string Language { get; set; }
    public string Description { get; set; }
    public string CompleteDescription { get; set; }
    public double Price { get; set; }
    public List<ProductFeature> Features { get; set; }

    public double AdditionalWeight { get; set; }
    public double PackageWeight { get; set; }

    public ProductStatus ProductStatus { get; set; }
}
public class ProductFeature
{
    public string FeatureName { get; set; }
    public List<FeatureOption> Options { get; set; }

}
public class FeatureOption
{
    public string Description { get; set; }
    public decimal AdditionalPrice { get; set; }
    public string Type { get; set; }
}
```

**Comment by atheken** [comment]
Try this, instead..
long count = db.GetCollection().Count();

Also, have you inserted anything into the collection yet? I would recommend that you email the Google Group if this issue persists.

**Comment by ti24horas** [comment]
Doing the above works as expected. I think that "Count" after "FindAll" should work. The query sent to the server is wrong doing those steps. Anyway, ill adapt my application to call Count command as explained above. Thanks.
