### ISSUE TITLE
Serializing custom types (proposal)

### ISSUE THREAD

**Issue by davidcanadas** [atheken/NoRM#16]
I'm using NoRM from a month ago and tried to implement everything I needed on my own classes instead of customizing the library (I consider modifying third-party code is a bad practice).

Now I've found I need to use a custom data type that should serialize to a primitive type. E.g., i want a "UnixTime" class that stores to the DB as a long, e.g.:

class MiClass {
  public ObjectId _id { get; set; }
  public UnixTime time { get; set; }
}

In the database, I don't want to store a "time: { seconds: 0 }", instead I want "time: 0".

To do that I should modify the BSONSerializer and BSONDeserializer classes, or to create an ignored property to work with UnixTime, then a property of type long with the long value for the UnixTime.

I think should be cool if NoRM supports at least one of those:
- Classes implementing TypeConverter uses it to serialize and deserialize (I think is the best choice).
- Classes with ISerializable serializes using Parse() and ToString().

**Comment by atheken** [comment]
We're working on a solution where the TypeConverters are pluggable into the BSON serializer, soon.
