### ISSUE TITLE
Non serializable types

### ISSUE THREAD

**Issue by davidcanadas** [atheken/NoRM#17]
Due to a caching system that I've implemented on top of Norm, I need to serialize Mongo records using system serializers. Unfortunately, I've had to manually modify the ObjectId type (the one I use right now) to add the [Serializable] attribute and allow, then, the record to be serialized.

I think that in-record data types should be serializable by default.

**Comment by atheken** [comment]
I'm not sure what you mean by "in-record data types"? can you include a class definition for one of the classes you're having trouble serializing?

**Comment by davidcanadas** [comment]
Sorry about my English... I mean any data type suitable to be in a Mongo collection item, e.g.:

[Serializable]
class Article {
  public ObjectId _id { get; set; }
}

Class "Article" is serializable, but "ObjectId" isn't, so I can't serialize without modifying the ObjectId.cs file, that is a bad practice :P

**Comment by atheken** [comment]
If you correct this in a fork, I will be happy to merge this.

**Comment by maate** [comment]
Hi, I have fixed this in this pull request: https://github.com/atheken/NoRM/pull/53.
Br. Morten
