### ISSUE TITLE
Json.Net support

### ISSUE THREAD

**Issue by petriashev** [atheken/NoRM#18]
Json.Net is powerfull and customizable product. Can you add support for Json.Net as pluggable serializer?

**Comment by atheken** [comment]
This is something that we might to in a release after 1.0, as our serializer is already quite powerful, and tailored to work with MongoDB (the focus of the NoRM project), I don't want to create additional complexity where it is not needed. Consider raising this request in the Google Group, or implementing it in a form and we'll look into merging it.
