### ISSUE TITLE
Support for custom type mappers to/from BSON type

### ISSUE THREAD

**Issue by petriashev** [atheken/NoRM#19]
Offen I need to store document with not supported types (TimeSpan,CultureInfo,other)
It will be nice to have ability to set type mappers to/from BSON type

for example:
TimeSpan -> BSON = TimeSpan.Ticks
CultureInfo -> BSON = CultureInfo.GetWebName()

**Comment by petriashev** [comment]
See discussion in http://github.com/atheken/NoRM/issues/#issue/9

**Comment by atheken** [comment]
I am going to merge JornWildt's type converter code, which should take care of this.
