### ISSUE TITLE
Gem for NoRM

### ISSUE THREAD

**Issue by mikeobrien** [atheken/NoRM#26]
Andrew,

I added a gem for NoRM 0.9.7 to rubygems.org. If you're interested in keeping it updated let me know the email address associated with your rubygems.org account and I can add you as an owner. I'm starting to use nu (The gem tool for .NET: http://bit.ly/dvd7gJ) and wanted to make this available via that mechanism. 

Here is the rake task I used to generate the gem if your interested: http://gist.github.com/504594

Thanks!

m

**Comment by atheken** [comment]
That's very cool. My account is "atheken" (very creative, I know). I am happy to try to keep it up to date.

**Comment by mikeobrien** [comment]
Excellent, thx! Rubygems.org uses the email associated with the rubygems account to add ownership. You can DM it to me if you want, and I'll add you on (@hcoverlambda).

**Comment by atheken** [comment]
theken.1@osu.edu

I know your handle, I follow you, dude :-)

**Comment by mikeobrien** [comment]
Excellent! I just added you on. Also pushed 0.9.8.

**Comment by mikeobrien** [comment]
Here is the updated Rake task. Added the dependency for log4net: http://gist.github.com/519827
