### ISSUE TITLE
Problematic 'Save' for entities with ID of  types int? and long?

### ISSUE THREAD

**Issue by froyke** [atheken/NoRM#28]
I think there is a problem with the (MongoCollectionGeneric) Save(T entity).
nullable int and longs are directed to Insert flow instead of update.

The expression:

```
       if (id == null && 
            (typeof(ObjectId).IsAssignableFrom(idProperty.Type)) ||
            (typeof(long?).IsAssignableFrom(idProperty.Type)) ||
            (typeof(int?).IsAssignableFrom(idProperty.Type)) )
```

is problematic since Long? and int? are always entering - whether if null or not.
Solution: () should be added over all || cases.

**Comment by schotime** [comment]
This has already been fixed in the current source.
Thanks for reporting the problem.
