### ISSUE TITLE
Add support for server status

### ISSUE THREAD

**Issue by jasona** [atheken/NoRM#3]
> db.$cmd.findOne({serverStatus:1})
> {
>         "uptime" : 275387,
>         "globalLock" : {
>                 "totalTime" : 275386956000,
>                 "lockTime" : 1300000,
>                 "ratio" : 0.000004720630268341395
>         },
>         "mem" : {
>                 "resident" : 2,
>                 "virtual" : 887,
>                 "supported" : true,
>                 "mapped" : 848
>         },
>         "ok" : 1
> }

(just putting this in so I don't forget)

**Comment by atheken** [comment]
already implemented this :-)

**Comment by jasona** [comment]
Haha! Whoops, ServerStatus() - there it is! :)
