### ISSUE TITLE
Sign NoRM

### ISSUE THREAD

**Issue by darrenkopp** [atheken/NoRM#31]
NoRM can't be referenced from a strongly named assembly right now since it doesn't have a strong name key and is not signed. Could you please create a key so that it can be signed.

**Comment by oliverw** [comment]
I second this. I had to dynamically load NoRM for the LINQPad Driver I wrote :)

**Comment by atheken** [comment]
I added an .snk file to the unstable branch, I think this is all that's required to sign the dll?

**Comment by darrenkopp** [comment]
well, you have to mark it in the project to sign it, although the minimum of having the key there is fine because anyone can then sign it and build it themselves, and be forward compatible if in the future you decide to sign it in the main build.

**Comment by atheken** [comment]
thanks for the info. I will look into doing it, I am using MonoDevelop for all c# development now, and haven't done much with the signing (haven't needed GAC installation for anything).
