### ISSUE TITLE
Connection string exception

### ISSUE THREAD

**Issue by eNepper** [atheken/NoRM#40]
I get the exception: The connection string passed does not appear to be a valid Uri, it should be of the form: 'mongodb[rs]://[user:password]@host:[port]/[replicaSetName]/dbname?[options]' where the parts in brackets are optional.

The problem is that my connection string contains a #

**Comment by schotime** [comment]
What is your connection string? and why does there need to be a # in it?

**Comment by eNepper** [comment]
mongodb://username:password@host:port/database
It's the password that contains a #

**Comment by atheken** [comment]
I would consider encoding the # in the password to "%23" and see if that takes care of you.
