### ISSUE TITLE
Stomping properties.

### ISSUE THREAD

**Issue by atheken** [atheken/NoRM#5]
Updates should only alter properties that are defined on the document, and should leave other properties untouched when updating.

**Comment by doxavore** [comment]
If you do this, then how do you later add properties to a document?

**Comment by atheken** [comment]
sorry, to be clear, if a class definition has this layout:

public class PlainPOCO{
   public int ID{get;set;}
public String Name {get;set;}
}

but the database has a property called "CreationDate", updating via norm should not cause that property to be lost..
if I change the definition to include:

public DateTime CreationDate{get;set;}

then it should be handled properly by NoRM, make sense?

**Comment by doxavore** [comment]
That makes sense - I was reading it as the reverse of that. =)

**Comment by hyrmn** [comment]
This feature would be incredibly useful. All you'd need to do is issue an .update(matchDoc, {$set {updateDoc} })

Any elements not in the $set are untouched. Any elements in the $set are replaced/added.

**Comment by atheken** [comment]
a simpler approach is to just reflect over what's defined on the class definition and build the spec document based on that. If you could have set it in c# but nulled it, the it should be set to null in the db.

$set/$unset should also be supported, but for different reasons, I think.
