### ISSUE TITLE
Cannon insert expando object

### ISSUE THREAD

**Issue by alexjamesbrown** [atheken/NoRM#62]
Trying to do the following:

```
var col = mongo.GetCollection<Expando>("mydoc");
col.Insert(new Expando(new { Id = "something", SomeProperty = "some value" }));
```

Throws error "This collection does not accept insertions/updates, this is due to the fact that the collection's type Norm.BSON.Expando does not specify an identifier property"

Want to be able to insert an anonymous typed document... without having to specify a class

**Comment by atheken** [comment]
Please try this instead:

  var col = mongo.GetCollection<Object>("mydoc");
  col.Insert(new { Id = "something", SomeProperty = "some value" });

**Comment by alexjamesbrown** [comment]
Thanks,
The insert method works with above, but not Save
