### ISSUE TITLE
Multi-threading issue

### ISSUE THREAD

**Issue by amirshim** [atheken/NoRM#7]
Norm.ConnectionProviderFactory is not multithread safe. (but pretends to be :)  It has a double lock pattern that will not work since _cachedBuilders's TryGetValue() is not an atomic operation. i.e. TryGetValue() (outside the lock) might be running at the same time as Add() on the same dictionary. A simple solution is copy on write.

**Comment by amirshim** [comment]
BTW... the likelihood of it happening are small.

**Comment by atheken** [comment]
Any chance you could commit a test to the repo or email the google group with a test?

**Comment by amirshim** [comment]
I don't think it makes sense for a unit test in this case, but check out:
http://stackoverflow.com/questions/2624301/how-to-show-that-the-double-checked-lock-pattern-with-dictionarys-trygetvalue-is

**Comment by henninga** [comment]
Will this throw an exception of some kind? Looking at some speed optimizations including caching of the results. Not sure how to approach the multithreading situation.
